"""Extension skeleton generator — generates tool/middleware/subagent scaffolds.

Generates standard extension files with:
- Proper imports and ExtensionMeta
- Registration decorator
- Build function pattern
- Test template with basic assertions
- Documentation stub

Usage::

    from agentbase.core.scaffold import generate_tool_scaffold

    generate_tool_scaffold(
        name="my_tool",
        description="Does something useful",
        output_dir=Path("."),
    )
    # → extensions/tools/my_tool.py
    # → tests/test_tool_my_tool.py
"""
from __future__ import annotations

import re
from pathlib import Path

from agentbase.runtime.logging import get_logger

logger = get_logger(__name__)


def _validate_name(name: str) -> str:
    """Validate that a name is a valid Python identifier (snake_case).

    Returns the validated name, or raises ValueError.
    """
    if not name:
        raise ValueError("Extension name cannot be empty")
    if not re.match(r"^[a-z][a-z0-9_]*$", name):
        raise ValueError(
            f"Invalid extension name '{name}': must be snake_case "
            "(lowercase, start with letter, only letters/digits/underscores)"
        )
    return name


def _to_class_name(snake_name: str) -> str:
    """Convert snake_case to PascalCase for class names."""
    return "".join(part.capitalize() for part in snake_name.split("_"))


# ---------------------------------------------------------------------------
# Tool scaffold template
# ---------------------------------------------------------------------------

_TOOL_TEMPLATE = '''"""Tool: {description}

Generated by `agentbase add-extension tool --name {name}`.

Customize the tool function below, then add "{name}" to your agent's
tools list in configs/agents/default.yaml.

Usage in agent config::

    tools:
      - {name}
"""
from __future__ import annotations

from typing import Any

from langchain_core.tools import tool

from agentbase.extensions._meta import ExtensionMeta
from agentbase.registry.tools import register_tool

_META = ExtensionMeta(
    name="{name}",
    kind="tool",
    description="{description}",
    requires_context=[],  # Add context keys if needed (e.g. "workspace_dir")
    default_enabled=False,  # Set to True to enable by default
)


@register_tool("{name}", meta=_META)
def build_{name}_tool(context: dict[str, Any] | None = None):
    """Build the {name} tool instance.

    Args:
        context: Shared context dict from the agent factory.
            Available keys depend on agent config.

    Returns:
        A LangChain tool instance.
    """
    # Access context if needed
    # workspace = (context or {{}}).get("workspace_dir", ".")

    @tool
    def {name}(input_text: str) -> str:
        """{description}

        Args:
            input_text: Input text for the tool.

        Returns:
            The tool's output.
        """
        # TODO: Implement your tool logic here
        return f"{{input_text}} (processed by {name})"

    return {name}
'''

_TOOL_TEST_TEMPLATE = '''"""Tests for the {name} tool."""
from __future__ import annotations

import pytest

from agentbase.extensions.tools.{name} import build_{name}_tool


class Test{name_class}:
    def test_build_returns_tool(self):
        """Build function should return a callable tool."""
        t = build_{name}_tool(context={{}})
        assert t is not None
        assert callable(t)

    def test_tool_invocation(self):
        """Tool should process input and return a string."""
        t = build_{name}_tool(context={{}})
        result = t.invoke("hello")
        assert isinstance(result, str)
        assert len(result) > 0

    def test_tool_with_context(self):
        """Tool should accept context dict."""
        t = build_{name}_tool(context={{"workspace_dir": "/tmp"}})
        assert t is not None

    def test_tool_with_none_context(self):
        """Tool should handle None context."""
        t = build_{name}_tool(context=None)
        assert t is not None
'''


def generate_tool_scaffold(
    *,
    name: str,
    description: str = "",
    output_dir: Path = Path("."),
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, str]:
    """Generate a tool extension scaffold.

    Creates two files:
    - ``extensions/tools/{name}.py`` — the tool implementation
    - ``tests/test_tool_{name}.py`` — the test template

    Args:
        name: Tool name (snake_case, e.g. ``"my_tool"``).
        description: Human-readable description.
        output_dir: Root directory for the project.
        force: Overwrite existing files.
        dry_run: Don't write files, just return what would be created.

    Returns:
        Dict mapping relative file paths to their content.
    """
    name = _validate_name(name)
    desc = description or f"Tool: {name}"
    name_class = _to_class_name(name)

    tool_content = _TOOL_TEMPLATE.format(name=name, description=desc)
    test_content = _TOOL_TEST_TEMPLATE.format(
        name=name, name_class=name_class, description=desc,
    )

    tool_path = output_dir / "extensions" / "tools" / f"{name}.py"
    test_path = output_dir / "tests" / f"test_tool_{name}.py"

    files = {
        str(tool_path): tool_content,
        str(test_path): test_content,
    }

    if not dry_run:
        for path_str, content in files.items():
            path = Path(path_str)
            if path.exists() and not force:
                logger.warning("File already exists: %s (use --force to overwrite)", path)
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            logger.info("Created: %s", path)

    return files


# ---------------------------------------------------------------------------
# Middleware scaffold template
# ---------------------------------------------------------------------------

_MW_TEMPLATE = '''"""Middleware: {description}

Generated by `agentbase add-extension middleware --name {name}`.

Customize the middleware below, then add "{name}" to your agent's
middleware list in configs/agents/default.yaml.

Usage in agent config::

    middleware:
      - {name}
"""
from __future__ import annotations

from typing import Any, Callable

from agentbase.extensions._meta import ExtensionMeta
from agentbase.registry.middleware import register_middleware

_META = ExtensionMeta(
    name="{name}",
    kind="middleware",
    description="{description}",
    requires_context=[],  # Add context keys if needed
    default_enabled=False,
)


@register_middleware("{name}", meta=_META)
def build_{name}(context: dict[str, Any] | None = None):
    """Build the {name} middleware.

    Returns a function that wraps an invoke function.
    """
    context = context or {{}}

    def {name}_invoke(invoke_fn: Callable[..., Any]) -> Callable[..., Any]:
        """Wrap an invoke function with {name} middleware."""

        def wrapped_invoke(*, agent_name: str = "default", **kwargs: Any) -> Any:
            # TODO: Add middleware logic here (before/after invoke)
            # Pre-processing
            result = invoke_fn(agent_name=agent_name, **kwargs)
            # Post-processing
            return result

        return wrapped_invoke

    return {name}_invoke
'''

_MW_TEST_TEMPLATE = '''"""Tests for the {name} middleware."""
from __future__ import annotations

import pytest

from agentbase.extensions.middleware.{name} import build_{name}


class Test{name_class}Middleware:
    def test_build_returns_wrapper(self):
        """Build function should return a wrapper function."""
        wrapper = build_{name}(context={{}})
        assert wrapper is not None
        assert callable(wrapper)

    def test_wrapper_passes_through(self):
        """Wrapper should pass invoke through and return result."""
        wrapper = build_{name}(context={{}})

        def mock_invoke(*, agent_name="default", **kwargs):
            return {{"result": "ok"}}

        wrapped = wrapper(mock_invoke)
        result = wrapped(agent_name="test")
        assert result == {{"result": "ok"}}

    def test_wrapper_with_none_context(self):
        """Wrapper should handle None context."""
        wrapper = build_{name}(context=None)
        assert wrapper is not None
'''


def generate_middleware_scaffold(
    *,
    name: str,
    description: str = "",
    output_dir: Path = Path("."),
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, str]:
    """Generate a middleware extension scaffold.

    Creates two files:
    - ``extensions/middleware/{name}.py`` — the middleware implementation
    - ``tests/test_middleware_{name}.py`` — the test template
    """
    name = _validate_name(name)
    desc = description or f"Middleware: {name}"
    name_class = _to_class_name(name)

    mw_content = _MW_TEMPLATE.format(name=name, description=desc)
    test_content = _MW_TEST_TEMPLATE.format(
        name=name, name_class=name_class, description=desc,
    )

    mw_path = output_dir / "extensions" / "middleware" / f"{name}.py"
    test_path = output_dir / "tests" / f"test_middleware_{name}.py"

    files = {
        str(mw_path): mw_content,
        str(test_path): test_content,
    }

    if not dry_run:
        for path_str, content in files.items():
            path = Path(path_str)
            if path.exists() and not force:
                logger.warning("File already exists: %s (use --force to overwrite)", path)
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            logger.info("Created: %s", path)

    return files
